<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "relax5validator"
 *
 * Auto generated by Extension Builder 2017-05-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'relax5validator',
    'description' => 'relax5validator provides a general validation service. The validation creteria (invariants) are stored in a database table.',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.2-rc80128',
    'constraints' => [
        'depends' => [
            'typo3' => '8.6.0-8.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
